# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac600b08ae49e3d295efde9b5d752b25b5e1edcd7c4370983b64944ebbbaf52b83f89ddc1c2ccf273a80cb3e0227371429dcc68c05e4b85b6210438ab7634c13

test:
  secret_key_base: d6aaceb14c0953beeab51891ec022d3f65141d44aeecd79771bdef9c05da7f0a549939f0cad59d3e626845e4d02b839e366b2441c2c2fdfd31162ddb06f6014b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
